sudo: false
os:
  - linux
language: node_js
node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "4"
  - "5"
env:
  global:
    - secure: ewqsRnX7z3+g6q+mM6peRPhuTlTlkJIRmVG/Ya9AcDXEb7as49KDTdqfMcOu7+FxF50ehqla+TRRCLRPOcVkWqs72OVUXEsjRASp9jQwpQGl+g/vZhyTMwlM2ENEkyiFQtobI1hYKgVW1ogftkc6vm7ywvoyTrFp/leVJBrTuHk=
    - secure: toafrATgXpnFcnvIeQvMK3gg0F5dxd+TI07RsukfnxGBCpTUJW/WnIS5y/2dvhtqWqopc+omivWTCDqU4ghYT24SZ1mO2CW+zP1n1FifzV8dUVVBenu0kbLzwbEhSE2J0u+cr4CfpPFiN7+GU2vndb41yGm/CK2qwO8snr6UwCs=
  matrix:
    - TEST_SUITE='npm run unit'
matrix:
  include:
    - node_js: "4"
      env: TEST_SUITE='npm run lint'
    - node_js: "4"
      env: TEST_SUITE='grunt coveralls'
    - node_js: "4"
      env: TEST_SUITE='grunt saucelabs'
  allow_failures:
    - env: TEST_SUITE='grunt saucelabs'
fast_finish: true
cache:
  directories:
    - node_modules
before_script:
  - npm install -g grunt-cli
script:
  - $TEST_SUITE
